#!/bin/sh

if [ "$1" == "" ]; then
	echo "Usage: vpk-xplore <dir_file>"
	echo "WARNING: It's just a shell script wrapping vpk-cli. vpk-cli should be located in the same drirectory with vpk-xplore for this to function"
	echo "WARNING: fzf and cut are required to run this script"
	echo "Opens an fzf menu with all resources found in a dir VPK."
	echo "Press ENTER to extract selected resource in the current directory, press Ctrl+C to cancel and exit the program."
	exit 1
fi

BASEDIR=$(dirname "$0")
RESOURCE=`$BASEDIR/vpk-cli -l "$1" | fzf`
R_EXT=`echo "$RESOURCE" | cut -f1 -d\ `
R_PATH=`echo "$RESOURCE" | cut -f2 -d\ `

if [ "$RESOURCE" == "" ]; then
	echo "Extraction aborted, exiting..."
	exit 1
fi

$BASEDIR/vpk-cli -i -o $(basename "$R_PATH").$R_EXT -e $R_EXT "$1" "$R_PATH"
